-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 18:34:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema grupo_1_hechoAmano
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grupo_1_hechoAmano
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grupo_1_hechoAmano` DEFAULT CHARACTER SET utf8 ;
USE `grupo_1_hechoAmano` ;

-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Categories` (
  `idCategory` INT NOT NULL,
  `nameCategory` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Sections` (
  `idSection` INT NOT NULL,
  `nameSection` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `seller` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10) NOT NULL,
  `stock` INT NULL,
  `payment` INT NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `shipping` INT NOT NULL,
  `discount` DECIMAL(10) NULL,
  `idCategory` INT NOT NULL,
  `idSection` INT NOT NULL,
  `idProducsUsers` INT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `idCategory` (`idCategory` ASC),
  INDEX `idSection` (`idSection` ASC),
  CONSTRAINT `FK_Categories_Products`
    FOREIGN KEY (`idCategory`)
    REFERENCES `grupo_1_hechoAmano`.`Categories` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sections_Products`
    FOREIGN KEY (`idSection`)
    REFERENCES `grupo_1_hechoAmano`.`Sections` (`idSection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`CategoriesUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`CategoriesUsers` (
  `idCategoriesUsers` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCategoriesUsers`),
  INDEX `idUser` (`idUser` ASC),
  INDEX `idCategory` (`idCategory` ASC),
  CONSTRAINT `FK_Categories_Users`
    FOREIGN KEY (`idCategory`)
    REFERENCES `grupo_1_hechoAmano`.`Categories` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Users_Categories`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Products_has_ProductUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Products_has_ProductUsers` (
  `Products_idProducts` INT NOT NULL,
  `ProductUsers_idProductUsers` INT NOT NULL,
  PRIMARY KEY (`Products_idProducts`, `ProductUsers_idProductUsers`),
  INDEX `fk_Products_has_ProductUsers_Products1_idx` (`Products_idProducts` ASC),
  CONSTRAINT `fk_Products_has_ProductUsers_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `grupo_1_hechoAmano`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Users_has_ProductUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Users_has_ProductUsers` (
  `idUsers` INT NOT NULL,
  `idProducts` INT NOT NULL,
  PRIMARY KEY (`idUsers`, `idProducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`TypeUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`TypeUsers` (
  `idTypeUser` INT NOT NULL,
  `nameType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTypeUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Countries` (
  `idCountry` INT NOT NULL,
  `nameCountry` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Users` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(200) NOT NULL,
  `idTypeUser` INT NOT NULL,
  `idCountry` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `idTypeUser` (`idTypeUser` ASC),
  INDEX `idCountry` (`idCountry` ASC),
  CONSTRAINT `FK_TypeUsers_Users`
    FOREIGN KEY (`idTypeUser`)
    REFERENCES `grupo_1_hechoAmano`.`TypeUsers` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Countries_Users`
    FOREIGN KEY (`idCountry`)
    REFERENCES `grupo_1_hechoAmano`.`Countries` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`ShoppingCart` (
  `idShoppingCart` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `totalPrice` DECIMAL(2) NOT NULL,
  `priceItem` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idShoppingCart`),
  INDEX `idUser` (`idUser` ASC),
  CONSTRAINT `FK_Users_ShoppingCart`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`CategoriesUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`CategoriesUsers` (
  `idCategoriesUsers` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCategoriesUsers`),
  INDEX `idUser` (`idUser` ASC),
  INDEX `idCategory` (`idCategory` ASC),
  CONSTRAINT `FK_Categories_Users`
    FOREIGN KEY (`idCategory`)
    REFERENCES `grupo_1_hechoAmano`.`Categories` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Users_Categories`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`ProductsUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`ProductsUsers` (
  `idProductsUsers` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `idUser` INT NOT NULL,
  `status` VARCHAR(100) NULL,
  PRIMARY KEY (`idProductsUsers`),
  INDEX `idProduct` (`idProduct` ASC),
  INDEX `idUser` (`idUser` ASC),
  CONSTRAINT `FK_Products_Users`
    FOREIGN KEY (`idProduct`)
    REFERENCES `grupo_1_hechoAmano`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Users_Products`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`ProductsShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`ProductsShoppingCart` (
  `idProductsShoppingCart` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `idShoppingCart` INT NOT NULL,
  PRIMARY KEY (`idProductsShoppingCart`),
  INDEX `idProduct` (`idProduct` ASC),
  INDEX `idShoppingCart` (`idShoppingCart` ASC),
  CONSTRAINT `FK_Products_ShoppingCart`
    FOREIGN KEY (`idProduct`)
    REFERENCES `grupo_1_hechoAmano`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ShoppingCart_Products`
    FOREIGN KEY (`idShoppingCart`)
    REFERENCES `grupo_1_hechoAmano`.`ShoppingCart` (`idShoppingCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 18:34:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema grupo_1_hechoAmano
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grupo_1_hechoAmano
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grupo_1_hechoAmano` DEFAULT CHARACTER SET utf8 ;
USE `grupo_1_hechoAmano` ;

-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Categories` (
  `idCategory` INT NOT NULL,
  `nameCategory` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Sections` (
  `idSection` INT NOT NULL,
  `nameSection` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `seller` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10) NOT NULL,
  `stock` INT NULL,
  `payment` INT NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `shipping` INT NOT NULL,
  `discount` DECIMAL(10) NULL,
  `idCategory` INT NOT NULL,
  `idSection` INT NOT NULL,
  `idProducsUsers` INT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `idCategory` (`idCategory` ASC),
  INDEX `idSection` (`idSection` ASC),
  CONSTRAINT `FK_Categories_Products`
    FOREIGN KEY (`idCategory`)
    REFERENCES `grupo_1_hechoAmano`.`Categories` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sections_Products`
    FOREIGN KEY (`idSection`)
    REFERENCES `grupo_1_hechoAmano`.`Sections` (`idSection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`CategoriesUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`CategoriesUsers` (
  `idCategoriesUsers` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCategoriesUsers`),
  INDEX `idUser` (`idUser` ASC),
  INDEX `idCategory` (`idCategory` ASC),
  CONSTRAINT `FK_Categories_Users`
    FOREIGN KEY (`idCategory`)
    REFERENCES `grupo_1_hechoAmano`.`Categories` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Users_Categories`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Products_has_ProductUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Products_has_ProductUsers` (
  `Products_idProducts` INT NOT NULL,
  `ProductUsers_idProductUsers` INT NOT NULL,
  PRIMARY KEY (`Products_idProducts`, `ProductUsers_idProductUsers`),
  INDEX `fk_Products_has_ProductUsers_Products1_idx` (`Products_idProducts` ASC),
  CONSTRAINT `fk_Products_has_ProductUsers_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `grupo_1_hechoAmano`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Users_has_ProductUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Users_has_ProductUsers` (
  `idUsers` INT NOT NULL,
  `idProducts` INT NOT NULL,
  PRIMARY KEY (`idUsers`, `idProducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`TypeUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`TypeUsers` (
  `idTypeUser` INT NOT NULL,
  `nameType` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTypeUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Countries` (
  `idCountry` INT NOT NULL,
  `nameCountry` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`Users` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(200) NOT NULL,
  `idTypeUser` INT NOT NULL,
  `idCountry` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `idTypeUser` (`idTypeUser` ASC),
  INDEX `idCountry` (`idCountry` ASC),
  CONSTRAINT `FK_TypeUsers_Users`
    FOREIGN KEY (`idTypeUser`)
    REFERENCES `grupo_1_hechoAmano`.`TypeUsers` (`idTypeUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Countries_Users`
    FOREIGN KEY (`idCountry`)
    REFERENCES `grupo_1_hechoAmano`.`Countries` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`ShoppingCart` (
  `idShoppingCart` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `totalPrice` DECIMAL(2) NOT NULL,
  `priceItem` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idShoppingCart`),
  INDEX `idUser` (`idUser` ASC),
  CONSTRAINT `FK_Users_ShoppingCart`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`CategoriesUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`CategoriesUsers` (
  `idCategoriesUsers` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCategoriesUsers`),
  INDEX `idUser` (`idUser` ASC),
  INDEX `idCategory` (`idCategory` ASC),
  CONSTRAINT `FK_Categories_Users`
    FOREIGN KEY (`idCategory`)
    REFERENCES `grupo_1_hechoAmano`.`Categories` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Users_Categories`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`ProductsUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`ProductsUsers` (
  `idProductsUsers` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `idUser` INT NOT NULL,
  `status` VARCHAR(100) NULL,
  PRIMARY KEY (`idProductsUsers`),
  INDEX `idProduct` (`idProduct` ASC),
  INDEX `idUser` (`idUser` ASC),
  CONSTRAINT `FK_Products_Users`
    FOREIGN KEY (`idProduct`)
    REFERENCES `grupo_1_hechoAmano`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Users_Products`
    FOREIGN KEY (`idUser`)
    REFERENCES `grupo_1_hechoAmano`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo_1_hechoAmano`.`ProductsShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo_1_hechoAmano`.`ProductsShoppingCart` (
  `idProductsShoppingCart` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  `idShoppingCart` INT NOT NULL,
  PRIMARY KEY (`idProductsShoppingCart`),
  INDEX `idProduct` (`idProduct` ASC),
  INDEX `idShoppingCart` (`idShoppingCart` ASC),
  CONSTRAINT `FK_Products_ShoppingCart`
    FOREIGN KEY (`idProduct`)
    REFERENCES `grupo_1_hechoAmano`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ShoppingCart_Products`
    FOREIGN KEY (`idShoppingCart`)
    REFERENCES `grupo_1_hechoAmano`.`ShoppingCart` (`idShoppingCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
